### ISSUE TITLE
Some fonts have too little contrast

### ISSUE THREAD

**Issue by chrisb86** [Neekster/MidnightTeal#2]
I just discovered the theme and I think it's awesome.

But I found some glitches. In some views (eg. the search dialog for adding cards to a dashboard) some fonts have way to little contrast and are barely recognbnizable.

I don't know enough about theme structures and stuff yet to prpose a fix.

But thanks for the theme!

**Comment by Neekster** [comment]
First of all, thanks for using this theme!

I've noticed this issue too, but I'm not really sure how to fix it. I'll be playing around with it in the next couple of days, and I'll release a new version if I find a fix.

**Comment by ImagineerNL** [comment]
came here for the same issue.
Wonderful theme though, but this makes it hard.
If you are able to set that text color to white for the dark teal version, like a bunch of other texts, it would help a lot

![image](https://user-images.githubusercontent.com/62603552/152646281-6a572c92-1c37-4f6a-b23c-92d9247e64b1.png)

@Neekster this seems to be linked to the " primary-color: "#197280" " but not sure what else is linked to it
(at least, in the css inspector in firefox, toggling --primary-color made the original color (lightblue) return

**Comment by Neekster** [comment]
Fixed in Version 1.8

**Comment by ImagineerNL** [comment]
Looks great, thank you
